################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c \
/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/list.c \
/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1/port.c \
/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/queue.c \
/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/timers.c 

OBJS += \
./Middlewares/FreeRTOS/cmsis_os.o \
./Middlewares/FreeRTOS/croutine.o \
./Middlewares/FreeRTOS/event_groups.o \
./Middlewares/FreeRTOS/heap_4.o \
./Middlewares/FreeRTOS/list.o \
./Middlewares/FreeRTOS/port.o \
./Middlewares/FreeRTOS/queue.o \
./Middlewares/FreeRTOS/stream_buffer.o \
./Middlewares/FreeRTOS/tasks.o \
./Middlewares/FreeRTOS/timers.o 

C_DEPS += \
./Middlewares/FreeRTOS/cmsis_os.d \
./Middlewares/FreeRTOS/croutine.d \
./Middlewares/FreeRTOS/event_groups.d \
./Middlewares/FreeRTOS/heap_4.d \
./Middlewares/FreeRTOS/list.d \
./Middlewares/FreeRTOS/port.d \
./Middlewares/FreeRTOS/queue.d \
./Middlewares/FreeRTOS/stream_buffer.d \
./Middlewares/FreeRTOS/tasks.d \
./Middlewares/FreeRTOS/timers.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/FreeRTOS/cmsis_os.o: /home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c Middlewares/FreeRTOS/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F767xx -DXPT2046_Swap_YD_and_YU -c -I../Inc -I../../Shared -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Device/ST/STM32F7xx/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -IC:/ST/Firmware/STM32AudioMiddlewares/Codecs/SpiritDSP_MP3_Dec/inc -Og -ffunction-sections -fdata-sections -Wall -Wno-main -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/FreeRTOS/cmsis_os.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/FreeRTOS/croutine.o: /home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/croutine.c Middlewares/FreeRTOS/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F767xx -DXPT2046_Swap_YD_and_YU -c -I../Inc -I../../Shared -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Device/ST/STM32F7xx/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -IC:/ST/Firmware/STM32AudioMiddlewares/Codecs/SpiritDSP_MP3_Dec/inc -Og -ffunction-sections -fdata-sections -Wall -Wno-main -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/FreeRTOS/croutine.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/FreeRTOS/event_groups.o: /home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c Middlewares/FreeRTOS/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F767xx -DXPT2046_Swap_YD_and_YU -c -I../Inc -I../../Shared -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Device/ST/STM32F7xx/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -IC:/ST/Firmware/STM32AudioMiddlewares/Codecs/SpiritDSP_MP3_Dec/inc -Og -ffunction-sections -fdata-sections -Wall -Wno-main -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/FreeRTOS/event_groups.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/FreeRTOS/heap_4.o: /home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c Middlewares/FreeRTOS/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F767xx -DXPT2046_Swap_YD_and_YU -c -I../Inc -I../../Shared -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Device/ST/STM32F7xx/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -IC:/ST/Firmware/STM32AudioMiddlewares/Codecs/SpiritDSP_MP3_Dec/inc -Og -ffunction-sections -fdata-sections -Wall -Wno-main -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/FreeRTOS/heap_4.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/FreeRTOS/list.o: /home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/list.c Middlewares/FreeRTOS/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F767xx -DXPT2046_Swap_YD_and_YU -c -I../Inc -I../../Shared -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Device/ST/STM32F7xx/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -IC:/ST/Firmware/STM32AudioMiddlewares/Codecs/SpiritDSP_MP3_Dec/inc -Og -ffunction-sections -fdata-sections -Wall -Wno-main -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/FreeRTOS/list.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/FreeRTOS/port.o: /home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1/port.c Middlewares/FreeRTOS/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F767xx -DXPT2046_Swap_YD_and_YU -c -I../Inc -I../../Shared -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Device/ST/STM32F7xx/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -IC:/ST/Firmware/STM32AudioMiddlewares/Codecs/SpiritDSP_MP3_Dec/inc -Og -ffunction-sections -fdata-sections -Wall -Wno-main -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/FreeRTOS/port.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/FreeRTOS/queue.o: /home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/queue.c Middlewares/FreeRTOS/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F767xx -DXPT2046_Swap_YD_and_YU -c -I../Inc -I../../Shared -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Device/ST/STM32F7xx/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -IC:/ST/Firmware/STM32AudioMiddlewares/Codecs/SpiritDSP_MP3_Dec/inc -Og -ffunction-sections -fdata-sections -Wall -Wno-main -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/FreeRTOS/queue.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/FreeRTOS/stream_buffer.o: /home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c Middlewares/FreeRTOS/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F767xx -DXPT2046_Swap_YD_and_YU -c -I../Inc -I../../Shared -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Device/ST/STM32F7xx/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -IC:/ST/Firmware/STM32AudioMiddlewares/Codecs/SpiritDSP_MP3_Dec/inc -Og -ffunction-sections -fdata-sections -Wall -Wno-main -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/FreeRTOS/stream_buffer.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/FreeRTOS/tasks.o: /home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/tasks.c Middlewares/FreeRTOS/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F767xx -DXPT2046_Swap_YD_and_YU -c -I../Inc -I../../Shared -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Device/ST/STM32F7xx/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -IC:/ST/Firmware/STM32AudioMiddlewares/Codecs/SpiritDSP_MP3_Dec/inc -Og -ffunction-sections -fdata-sections -Wall -Wno-main -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/FreeRTOS/tasks.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/FreeRTOS/timers.o: /home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4/Middlewares/Third_Party/FreeRTOS/Source/timers.c Middlewares/FreeRTOS/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F767xx -DXPT2046_Swap_YD_and_YU -c -I../Inc -I../../Shared -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Device/ST/STM32F7xx/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Drivers/CMSIS/Include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/include -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/home/jsb/STM32Cube/Repository/STM32Cube_FW_F7_V1.17.4//Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -IC:/ST/Firmware/STM32AudioMiddlewares/Codecs/SpiritDSP_MP3_Dec/inc -Og -ffunction-sections -fdata-sections -Wall -Wno-main -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/FreeRTOS/timers.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=softfp -mthumb -o "$@"

clean: clean-Middlewares-2f-FreeRTOS

clean-Middlewares-2f-FreeRTOS:
	-$(RM) ./Middlewares/FreeRTOS/cmsis_os.cyclo ./Middlewares/FreeRTOS/cmsis_os.d ./Middlewares/FreeRTOS/cmsis_os.o ./Middlewares/FreeRTOS/cmsis_os.su ./Middlewares/FreeRTOS/croutine.cyclo ./Middlewares/FreeRTOS/croutine.d ./Middlewares/FreeRTOS/croutine.o ./Middlewares/FreeRTOS/croutine.su ./Middlewares/FreeRTOS/event_groups.cyclo ./Middlewares/FreeRTOS/event_groups.d ./Middlewares/FreeRTOS/event_groups.o ./Middlewares/FreeRTOS/event_groups.su ./Middlewares/FreeRTOS/heap_4.cyclo ./Middlewares/FreeRTOS/heap_4.d ./Middlewares/FreeRTOS/heap_4.o ./Middlewares/FreeRTOS/heap_4.su ./Middlewares/FreeRTOS/list.cyclo ./Middlewares/FreeRTOS/list.d ./Middlewares/FreeRTOS/list.o ./Middlewares/FreeRTOS/list.su ./Middlewares/FreeRTOS/port.cyclo ./Middlewares/FreeRTOS/port.d ./Middlewares/FreeRTOS/port.o ./Middlewares/FreeRTOS/port.su ./Middlewares/FreeRTOS/queue.cyclo ./Middlewares/FreeRTOS/queue.d ./Middlewares/FreeRTOS/queue.o ./Middlewares/FreeRTOS/queue.su ./Middlewares/FreeRTOS/stream_buffer.cyclo ./Middlewares/FreeRTOS/stream_buffer.d ./Middlewares/FreeRTOS/stream_buffer.o ./Middlewares/FreeRTOS/stream_buffer.su ./Middlewares/FreeRTOS/tasks.cyclo ./Middlewares/FreeRTOS/tasks.d ./Middlewares/FreeRTOS/tasks.o ./Middlewares/FreeRTOS/tasks.su ./Middlewares/FreeRTOS/timers.cyclo ./Middlewares/FreeRTOS/timers.d ./Middlewares/FreeRTOS/timers.o ./Middlewares/FreeRTOS/timers.su

.PHONY: clean-Middlewares-2f-FreeRTOS

